"""add meta_info and source_conversation_id to knowledge_articles

Revision ID: 69e6c7beed04
Revises: 
Create Date: 2026-07-02 20:09:11.364868
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '69e6c7beed04'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_agent_runs_conv'), table_name='agent_runs')
    op.drop_index(op.f('idx_agent_runs_name'), table_name='agent_runs')
    op.alter_column('conversations', 'sentiment_trend',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('conversations', 'metadata',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.add_column('knowledge_articles', sa.Column('source_conversation_id', sa.UUID(), nullable=True))
    op.add_column('knowledge_articles', sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    op.alter_column('knowledge_articles', 'tags',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('knowledge_articles', 'status',
               existing_type=sa.VARCHAR(length=30),
               nullable=False,
               existing_server_default=sa.text("'draft'::character varying"))
    op.alter_column('knowledge_articles', 'effectiveness_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('knowledge_articles', 'usage_count',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.create_foreign_key(None, 'knowledge_articles', 'conversations', ['source_conversation_id'], ['id'])
    op.alter_column('messages', 'content_type',
               existing_type=sa.VARCHAR(length=30),
               nullable=False,
               existing_server_default=sa.text("'text'::character varying"))
    op.alter_column('messages', 'metadata',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.drop_index(op.f('idx_messages_conv'), table_name='messages')
    op.alter_column('users', 'tier',
               existing_type=sa.VARCHAR(length=30),
               nullable=False,
               existing_server_default=sa.text("'standard'::character varying"))
    op.alter_column('users', 'tags',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('users', 'metadata',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'metadata',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('users', 'tags',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('users', 'tier',
               existing_type=sa.VARCHAR(length=30),
               nullable=True,
               existing_server_default=sa.text("'standard'::character varying"))
    op.create_index(op.f('idx_messages_conv'), 'messages', ['conversation_id', 'created_at'], unique=False)
    op.alter_column('messages', 'metadata',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('messages', 'content_type',
               existing_type=sa.VARCHAR(length=30),
               nullable=True,
               existing_server_default=sa.text("'text'::character varying"))
    op.drop_constraint(None, 'knowledge_articles', type_='foreignkey')
    op.alter_column('knowledge_articles', 'usage_count',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('knowledge_articles', 'effectiveness_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('knowledge_articles', 'status',
               existing_type=sa.VARCHAR(length=30),
               nullable=True,
               existing_server_default=sa.text("'draft'::character varying"))
    op.alter_column('knowledge_articles', 'tags',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.drop_column('knowledge_articles', 'metadata')
    op.drop_column('knowledge_articles', 'source_conversation_id')
    op.alter_column('conversations', 'metadata',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('conversations', 'sentiment_trend',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.create_index(op.f('idx_agent_runs_name'), 'agent_runs', ['agent_name'], unique=False)
    op.create_index(op.f('idx_agent_runs_conv'), 'agent_runs', ['conversation_id'], unique=False)
    # ### end Alembic commands ###
